package presentationLayer;

import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JButton;

public class PrincipalWindow extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalPage
     */
    public PrincipalWindow() {
        initComponents();
        setTransparentButton(btPlay);
        setTransparentButton(btInscription);
        setTransparentButton(btModify);
        setTransparentButton(btToList);
        this.setSize(465, 553);
        ImageIcon icon1 = new ImageIcon("imagenes progra/maxresdefault.jpg");
        ImageIcon icon2 = new ImageIcon("Images/background.jpg");
        jlBackground.setIcon(icon2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btPlay = new javax.swing.JButton();
        btInscription = new javax.swing.JButton();
        btModify = new javax.swing.JButton();
        btToList = new javax.swing.JButton();
        jlImageIcon = new javax.swing.JLabel();
        jlBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btPlay.setBackground(new java.awt.Color(255, 255, 255));
        btPlay.setFont(new java.awt.Font("SimSun-ExtB", 1, 16)); // NOI18N
        btPlay.setForeground(new java.awt.Color(149, 17, 29));
        btPlay.setText("JUGAR");
        btPlay.setBorder(null);
        btPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, 40));

        btInscription.setFont(new java.awt.Font("SimSun-ExtB", 1, 16)); // NOI18N
        btInscription.setForeground(new java.awt.Color(149, 17, 29));
        btInscription.setText("INSCRIPCION");
        btInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInscriptionActionPerformed(evt);
            }
        });
        getContentPane().add(btInscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 160, 40));

        btModify.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        btModify.setForeground(new java.awt.Color(149, 17, 29));
        btModify.setText("MODIFICAR EQUIPO");
        getContentPane().add(btModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 160, 40));

        btToList.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        btToList.setForeground(new java.awt.Color(149, 17, 29));
        btToList.setText("LISTADO EQUIPOS");
        getContentPane().add(btToList, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 160, 40));

        jlImageIcon.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlImageIcon.setForeground(new java.awt.Color(255, 255, 255));
        jlImageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlImageIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER-PC\\Documents\\NetBeansProjects\\ProgramProjectI\\imagenes progra\\Escape-Room-Google-979x551.png")); // NOI18N
        getContentPane().add(jlImageIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 260, 90));

        jlBackground.setForeground(new java.awt.Color(255, 255, 255));
        jlBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER-PC\\Documents\\NetBeansProjects\\ProgramProjectI\\imagenes progra\\white-background-1920x1080-4.jpg")); // NOI18N
        jlBackground.setMaximumSize(new java.awt.Dimension(1200, 600));
        jlBackground.setMinimumSize(new java.awt.Dimension(1200, 600));
        jlBackground.setPreferredSize(new java.awt.Dimension(480, 430));
        getContentPane().add(jlBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlayActionPerformed

        Main.user.setLocationRelativeTo(null);
        Main.user.getButtonEnter().setVisible(true);
        Main.user.getButtonSave().setVisible(false);
        Main.user.getTfNickName().setVisible(false);
        Main.user.getLbNickName().setVisible(false);
        Main.user.getLbEmail().setText("Usuario");
        Main.user.setVisible(true);
    }//GEN-LAST:event_btPlayActionPerformed

    private void btInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInscriptionActionPerformed

    public void setTransparentButton(JButton button) {
        button.setOpaque(false);
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
    }

//    public void closeWindow(java.awt.event.WindowEvent evt) {
//        if (DISPOSE_ON_CLOSE == 2) {
//           
//        }
//    }
//
//    @Override
//    public void disable() {
//        super.disable(); //To change body of generated methods, choose Tools | Templates.
//    }

    @Override
    public void dispose() {
         try {
                Main.userInterfaceManager.writeInfo();
                System.out.println("ESCRIBE");
            } catch (IOException ex) {
                System.out.println("no escribio");
            }
        System.exit(0); //To change body of generated methods, choose Tools | Templates.
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInscription;
    private javax.swing.JButton btModify;
    private javax.swing.JButton btPlay;
    private javax.swing.JButton btToList;
    private javax.swing.JLabel jlBackground;
    private javax.swing.JLabel jlImageIcon;
    // End of variables declaration//GEN-END:variables
}
