/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentationLayer;

import javax.swing.ImageIcon;

/**
 *
 * @author USER-PC
 */
public class SortList extends javax.swing.JDialog {
    
    /**
     * Creates new form SortList
     */
    public SortList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon icon1 = new ImageIcon("imagenes progra/white.jpg");
        lbBackground.setIcon(icon1);
        this.setSize(410,470);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jlSortList = new javax.swing.JScrollPane();
        sortList = new javax.swing.JList<>();
        btBack = new javax.swing.JButton();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(149, 29, 17));
        lbTitle.setText("LISTA ORDENADA");
        getContentPane().add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 160, 40));

        jlSortList.setViewportView(sortList);

        getContentPane().add(jlSortList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 359, 343));

        btBack.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        btBack.setForeground(new java.awt.Color(102, 102, 102));
        btBack.setText("REGRESAR");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        getContentPane().add(btBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 120, 30));
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        dispose();
    }//GEN-LAST:event_btBackActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JScrollPane jlSortList;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JList<String> sortList;
    // End of variables declaration//GEN-END:variables
}
